### ISSUE TITLE
allow for bottom-up ordering of results

### ISSUE THREAD

**Issue by mattp-** [Yggdroot/LeaderF#222] opened 2018-09-24 14:31 UTC
### Describe your question, feature request, or bug.
Currently the results are ordered top-down, (ie https://github.com/Yggdroot/Images/raw/master/leaderf/leaderf_2.gif)
1 is at the top, 2,3, etc following downward. It would be nice to be able to reverse this so the most likely file to open is at the bottom, similar to how ctrl-p works:
https://camo.githubusercontent.com/0a0b4c0d24a44d381cbad420ecb285abc2aaa4cb/687474703a2f2f692e696d6775722e636f6d2f7949796e722e706e67

**Comment by Yggdroot** [comment] 2018-09-26 07:11
Duplicate of #195 .

**Comment by Yggdroot** [comment] 2018-10-03 00:55
Added.

**Comment by mattp-** [comment] 2018-10-03 00:56
you're a champ 👍 thank you

**Closed** 2018-10-03 01:02 UTC
Labels: duplicate, feature request
