### ISSUE TITLE
Up/down arrow keys no longer work.

### ISSUE THREAD

**Issue by 9527KGG** [Yggdroot/LeaderF#236] opened 2018-10-18 18:43 UTC
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Steps to reproduce

Assume the tag names are: tag1, tag2, tag3.
In past, after :LeaderfTag, then input "tag". I can use "up/down" key to choose the one I want. If I find I type sth wrong, say I type "tbg". I can use backspace key to undo the change.

Now, after :LeaderfTag, then input "tag". I HAVE TO press tab key. Then use "up/down" key to choose the one I want. After press tab key, if I find I type sth wrong, say I type "tbg". I've to type i to goto to i mode to type backspace.

I think the new feature is not convenient. Basically, I've to type extra more to do the same thing as before. Is this change by design? If yes, may you please provide a global flag to switch to previous mode?

Thanks.

**Comment by Yggdroot** [comment] 2018-10-19 10:16
This feature is introduced by issue #213 . https://github.com/Yggdroot/LeaderF/commit/a64ea189a426444875ae2df4b69a991f7d5b7043
This issue is also a duplicate of #228 .
You can use `g:Lf_CommandMap` to change the key bindings.

**Comment by 9527KGG** [comment] 2018-10-19 16:11
Thanks. May you please tell me what's the exact definition of g:Lf_CommandMap I should use to recover previous behavior?

**Comment by Yggdroot** [comment] 2018-10-19 23:14
https://github.com/Yggdroot/LeaderF/blob/1b42185db9d58483d9e3eb6069075d28866ad150/doc/leaderf.txt#L590-L591
https://github.com/Yggdroot/LeaderF/blob/1b42185db9d58483d9e3eb6069075d28866ad150/doc/leaderf.txt#L484-L489

**Closed** 2020-06-08 10:48 UTC
Labels: FAQ, duplicate
