### ISSUE TITLE
.gitignore affect the Lf_WildIgnore in a git repo

### ISSUE THREAD

**Issue by znculee** [Yggdroot/LeaderF#217] opened 2018-09-11 03:28 UTC
- vim or neovim? 
    - [x] vim
    - [] neovim

- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
let g:Lf_WildIgnore={
  \ 'dir': ['.svn','.git','.hg'],
  \ 'file': ['*.sw?','~$*','*.o','*.so','*.pdf','*.gz',
           \ '.DS_Store','.localized','*.bak','*.exe',
           \ '*.py[co]','*.np[yz]']
  \ }

### Describe your question, feature request, or bug.
:LeaderfFile is affected by .gitignore file, after I installed vim-fungitive. 

### Steps to reproduce
mkdir tmp
touch tmp/tmp.txt
echo tmp > .gitignore
open vim, and run :LeaderfFile (tmp/tmp.txt will showup)
However, after `git init`, tmp/tmp.txt will not show.

### Expected behaviour
I do not want .gitignore affect Leaderf even in a git repo.

**Comment by Yggdroot** [comment] 2018-09-11 04:39
So you mean you want to ignore the .gitignore file?
If so, this is a duplicate of issue #194 .

**Comment by znculee** [comment] 2018-09-11 05:04
Thanks for your help! Besides, I think there is an option that do not ignore g:Lf_WildIgnore when UseVersionControlTool will be better.

**Closed** 2018-09-11 05:04 UTC
