### ISSUE TITLE
vim.error: Vim(redir):E930: Cannot use :redir inside execute()

### ISSUE THREAD

**Issue by ijpq** [Yggdroot/LeaderF#917] opened 2022-06-28 12:45 UTC
i had.

- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 19 2022 10:22:43)
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): blank
- Output of `:echo &pythonthreedll`(only vim, not neovim): blank
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.7.5 (default, Dec  9 2021, 17:04:37)
[GCC 8.4.0]

- Output of `:echo g:Lf_Debug_Cmd`:  undeinfed
- Output of `:echo g:Lf_FilesFromCache`:  1
- Operating system: 
    - [ x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
gtags has been generated successfully using gutantags
```bash
let g:Lf_ShortcutF = '<C-P>'
let g:Lf_ShortcutB = '<C-B>'
noremap <leader>fr :<C-U><C-R>=printf("Leaderf! gtags -r %s --auto-jump", expand("<cword>"))<CR><CR>
noremap <leader>fd :<C-U><C-R>=printf("Leaderf! gtags -d %s --auto-jump", expand("<cword>"))<CR><CR>
let g:Lf_CommandMap = {'<C-F>': ['<C-D>'], '<C-P>': ['p'], '<C-]>': ['<C-\>']}
nmap <C-F> <Plug>LeaderfRgPrompt
noremap <leader>ll :LeaderfFunction!<cr>
" nmap <C-p> :LeaderfFunction!<CR>
"
" attributes
let g:Lf_WindowPosition = 'bottom'
let g:Lf_PreviewCode = 1
" let g:Lf_PreviewHorizontalPosition = 'center'
let g:Lf_GtagsAutoGenerate = 0
let g:Lf_GtagsGutentags = 1
let g:Lf_CacheDirectory = expand('~')
let g:Lf_ShowDevIcons = 0
let g:Lf_StlSeparator = { 'left': '', 'right': '', 'font': '' }
let g:Lf_RootMarkers = ['.project', '.root', '.svn']
let g:Lf_WorkingDirectoryMode = 'Ac'
let g:Lf_WindowHeight = 0.30
" let s:leaderfcache=expand('~/.cache')
" if !isdirectory(s:leaderfcache)
"    silent! call mkdir(s:leaderfcache, 'p')
" endif
" let g:Lf_CacheDirectory = s:leaderfcache
let g:Lf_ShowRelativePath = 0
let g:Lf_HideHelp = 1
let g:Lf_StlColorscheme = 'powerline'
let g:Lf_PreviewResult = {'Function':1, 'BufTag':0, 'File':0, 'Gtags':0}

```
### Describe your question, feature request, or bug.
using gtags find a list of function definitions, when preview at one line. 
messages  show up:
```bash
Error detected while processing :                                                                                                                                                                           
Traceback (most recent call last):                                                                                                                                                                          
  File "<string>", line 1, in <module>                                                                                                                                                                      
  File "/home/tangke/.vim_runtime/my_plugins/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 393, in _previewResult                                                                               
    self._previewInPopup(line, self._getInstance().buffer, line_nr)                                                                                                                                         
  File "/home/tangke/.vim_runtime/my_plugins/LeaderF/autoload/leaderf/python/leaderf/gtagsExpl.py", line 1233, in _previewInPopup                                                                           
    self._createPopupPreview("", source, line_num)                                                                                                                                                          
  File "/home/tangke/.vim_runtime/my_plugins/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 91, in deco                                                                                          
    func(self, *args, **kwargs)                                                                                                                                                                             
  File "/home/tangke/.vim_runtime/my_plugins/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 883, in _createPopupPreview                                                                          
    lfCmd("call win_execute(winid, 'doautocmd filetypedetect BufNewFile %s')" % escQuote(source))                                                                                                           
vim.error: Vim(redir):E930: Cannot use :redir inside execute() 
```

**Comment by Yggdroot** [comment] 2022-06-29 01:12
Duplicate of https://github.com/Yggdroot/LeaderF/issues/408.

**Comment by ijpq** [comment] 2022-06-29 01:48
> Duplicate of https://github.com/Yggdroot/LeaderF/issues/408.

Thx

**Closed** 2022-06-29 11:08 UTC
