### ISSUE TITLE
Error when using twice LeaderfFile

### ISSUE THREAD

**Issue by ChrisAmelia** [Yggdroot/LeaderF#617] opened 2020-06-05 06:42 UTC
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 

> NVIM v0.5.0-519-g74fed7d50
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-921020c4-4c26-40cf-812e-9d6ab07d1485
Features: +acl +iconv +tui

- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1
- Output of `:py print(sys.version)`:
> 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
- Output of `:py3 print(sys.version)`:
> 3.5.2 (default, Oct  8 2019, 13:06:37) [GCC 5.4.0 20160609]
- Output of `:echo g:Lf_Debug_Cmd`:
> rg --no-messages --files --color never
- Output of `:echo g:Lf_FilesFromCache`: 1
- Operating system:
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

```vim
set runtimepath^=~/.local/share/nvim/plugged/LeaderF
filetype plugin indent on
syntax on
set hidden
```

### Describe your question, feature request, or bug.

Got the following error when using twice `:Leaderf file`:

> Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy[1]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.local/share/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 797, in start
    the_args.start(arguments, *args, **kwargs)
  File "/home/user/.local/share/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 729, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/home/user/.local/share/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 808, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/home/user/.local/share/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2075, in startExplorer
    self.input()
  File "/home/user/.local/share/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 62, in deco
    func(self, *args, **kwargs)
  File "/home/user/.local/share/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2343, in input
    self._guessSearch(self._content)
  File "/home/user/.local/share/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1388, in _guessSearch
    _, self._result_content = self._filter(step, filter_method, content, is_continue, True)
  File "/home/user/.local/share/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1017, in _filter
    result = filter_method(source=cur_content)
TypeError: guessMatch() takes at most 6 arguments (7 given)

The first attempt is successful.  
On the second attempt, I cannot input any character, only select which file to open.
   
The responsible commit is c087cc51e8ae5423e29b9cf7fa428a4af97884cf
### Steps to reproduce

1. With above config, open nvim:

```vim
nvim -u init.vim
```

2. Type `:Leaderf file`. Select a file.

3. Type again `:Leaderf file`.

**Comment by Yggdroot** [comment] 2020-06-05 06:55
This is a duplicate of #616 .

**Closed** 2020-06-05 06:57 UTC
