### ISSUE TITLE
can't work with old git version: Exception: error: unknown option `recurse-submodules'

### ISSUE THREAD

**Issue by fcying** [Yggdroot/LeaderF#219] opened 2018-09-13 04:01 UTC
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: vim 8.1
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): none
- Output of `:echo &pythonthreedll`(only vim, not neovim): libpython3.5m.so.1.0
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.5.2 (default, Nov 23 2017, 16:37:01)[GCC 5.4.0 20160609]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
some server only have old git version, ex:`ubuntu 16.04` `git version 2.7.4`, it work error with leaderf.

```
Exception: error: unknown option `recurse-submodules'
usage: git ls-files [<options>] [<file>...]
    -z                    paths are separated with NUL character
    -t                    identify the file status with tags
    -v                    use lowercase letters for 'assume unchanged' files
    -c, --cached          show cached files in the output (default)
    -d, --deleted         show deleted files in the output
    -m, --modified        show modified files in the output
    -o, --others          show other files in the output
    -i, --ignored         show ignored files in the output
    -s, --stage           show staged contents' object name in the output
    -k, --killed          show files on the filesystem that need to be removed
    --directory           show 'other' directories' names only
    --eol                 show line endings of files
    --empty-directory     don't show empty directories
```

### Steps to reproduce
leaderf file

### Expected behaviour
workfine with old git version

**Comment by Yggdroot** [comment] 2018-09-13 04:15
This is a duplicate of issue #211 , perhaps I should fix it.

**Closed** 2018-09-13 07:01 UTC
Labels: duplicate
