### ISSUE TITLE
输入界面 command + v 会卡死整个vim

### ISSUE THREAD

**Issue by Fre-ak** [Yggdroot/LeaderF#739] opened 2020-12-17 02:29 UTC
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec  9 2020 10:54:11)
macOS version
包含补丁: 1-2100
编译者 Homebrew
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
3.9.1 (default, Dec 11 2020, 10:13:38)
[Clang 12.0.0 (clang-1200.0.32.27)
- Output of `:echo g:Lf_Debug_Cmd`: 
find  "." -name "." -o   -name ".*" -prune -o -type f -print  2>/dev/null | se
d 's#^\./##'
- Output of `:echo g:Lf_FilesFromCache`: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc:

**Comment by Yggdroot** [comment] 2020-12-17 03:11
Duplicate of #427 .

**Closed** 2020-12-18 02:05 UTC
