### ISSUE TITLE
LeaderfFile doesn't show files in MacVim.

### ISSUE THREAD

**Issue by wangyandong-ningxia** [Yggdroot/LeaderF#328] opened 2019-05-27 07:13 UTC
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 18 2019 23:51:40)
macOS version
Included patches: 1-950
Compiled by travis@Traviss-Mac.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
+autochdir         +float             +mouse_xterm       +terminal
-autoservername    +folding           +multi_byte        +terminfo
+balloon_eval      -footer            +multi_lang        +termresponse
+balloon_eval_term +fork()            -mzscheme          +textobjects
+browse            +fullscreen        +netbeans_intg     +textprop
++builtin_terms    -gettext           +num64             +timers
+byte_offset       -hangul_input      +odbeditor         +title
+channel           +iconv             +packages          +toolbar
+cindent           +insert_expand     +path_extra        +transparency
+clientserver      +job               +perl/dyn          +user_commands
+clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           +python/dyn        +visualextra
+conceal           +linebreak         +python3/dyn       +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       +lua/dyn           +ruby/dyn          +windows
+dialog_con_gui    +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             -X11
+digraphs          +modify_fname      +smartindent       -xfontset
+dnd               +mouse             +startuptime       +xim
-ebcdic            +mouseshape        +statusline        -xpm
+emacs_tags        +mouse_dec         -sun_workshop      -xsmp
+eval              -mouse_gpm         +syntax            -xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
+extra_search      +mouse_netterm     +tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE
```
- Output of `:echo has("python")`: 
```
0
```
- Output of `:echo has("python3")`: 
```
1
```
- Output of `:echo &pythondll`(only vim, not neovim): 
```
/usr/local/Frameworks/Python.framework/Versions/2.7/Python
```
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
```
/usr/local/Frameworks/Python.framework/Versions/3.7/Python
```
- Output of `:py print(sys.version)`: 
```
E836: This Vim cannot execute :python after using :py3
E263: Sorry, this command is disabled, the Python library could not be loaded.
```
- Output of `:py3 print(sys.version)`: 
```
3.7.3 (default, Mar 27 2019, 09:23:15)
[Clang 10.0.1 (clang-1001.0.46.3)]
```
- Output of `:echo g:Lf_Debug_Cmd`: 
```
ag --nocolor --silent     -g "" "."
```
- Output of `:echo g:Lf_FilesFromCache`: 
```
1
```
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
Plug 'Yggdroot/LeaderF', { 'do': './install.sh' }

" Use default settings of LeaderF
```

### Describe your question, feature request, or bug.

 LeaderfFile doesn't show files in MacVim, unless it is fired within some project directory, such as a git repository. It works fine within the terminal version of Vim.
(The terminal version of Vim is the one bundled with MacVim ```vim: aliased to mvim -v```)

### Steps to reproduce
Launch LeaderfFile within my $GOPATH, nothing shows in MacVim.
<img width="1149" alt="Screen Shot 2019-05-27 at 14 42 01" src="https://user-images.githubusercontent.com/5441476/58400986-3a66b900-808f-11e9-9d0a-1968575987fd.png">
<img width="1149" alt="Screen Shot 2019-05-27 at 14 42 33" src="https://user-images.githubusercontent.com/5441476/58400926-0ab7b100-808f-11e9-9eb3-f6da2dc8994e.png">
LeaderfFile works fine within terminal version of Vim.
<img width="1442" alt="Screen Shot 2019-05-27 at 14 41 56" src="https://user-images.githubusercontent.com/5441476/58400895-f4115a00-808e-11e9-9257-c5692cfebdd2.png">
<img width="1442" alt="Screen Shot 2019-05-27 at 14 42 28" src="https://user-images.githubusercontent.com/5441476/58400936-0ee3ce80-808f-11e9-9749-e389e29ed4f8.png">

If fired within a git repository in $GOPATH, it works fine again.
<img width="1149" alt="Screen Shot 2019-05-27 at 15 04 14" src="https://user-images.githubusercontent.com/5441476/58401742-320f7d80-8091-11e9-8b3e-6a54d46090ca.png">

### Actual behaviour
LeaderfFile doesn't show files in MacVim,  unless it is fired within some project directory.

### Expected behaviour
LeaderfFile in MacVim should work whether or not  fired within a project directory.

**Comment by Yggdroot** [comment] 2019-05-27 07:44
What is the output of the following command:
```python
:py3 import subprocess
:py3 print (subprocess.Popen('ag --nocolor --silent -g "" "." ', shell=True, stdout=subprocess.PIPE).stdout.read())
```

**Comment by wangyandong-ningxia** [comment] 2019-05-27 08:32
> This issue may be the bug of Macvim.
> What is the output of the following command:
> 
> ```python
> :py3 import subprocess
> :py3 print (subprocess.Popen('ag --nocolor --silent -g "" "." ', shell=True, stdout=subprocess.PIPE).stdout.read())
> ```

The output is ```b''```

**Comment by Yggdroot** [comment] 2019-05-27 08:37
What about the output on terminal vim?

**Comment by wangyandong-ningxia** [comment] 2019-05-27 09:00
> What about the output on terminal vim?

LeaderfFile @$GOPATH (Vim)
```
b'bin/impl\nbin/gorename\nbin/guru\nbin/gomodifytags\nbin/gotags\nbin/gopls\nbin/gocode-gomod\nbin/motion\nbin/golangci-
lint\nbin/errcheck\nbin/dlv\nbin/asmfmt\nbin/gocode\nbin/goimports\nbin/keyify\nbin/golint\nbin/iferr\nbin/gometalinter\
nbin/fillstruct\nbin/godef\nbin/gogetdoc\nsrc/wangyandong/socks5-server/main.go\nsrc/honnef.co/go/tools/cmd/rdeps/rdeps.
go\nsrc/honnef.co/go/tools/cmd/rdeps/README.md\nsrc/honnef.co/go/tools/cmd/structlayout-pretty/main.go\nsrc/honnef.co/go
/tools/cmd/staticcheck/README.md\nsrc/honnef.co/go/tools/cmd/staticcheck/staticcheck.go\nsrc/honnef.co/go/tools/cmd/mega
check/README.md\nsrc/honnef.co/go/tools/cmd/megacheck/megacheck.go\nsrc/honnef.co/go/tools/cmd/unused/README.md\nsrc/hon
nef.co/go/tools/cmd/unused/main.go\nsrc/honnef.co/go/tools/cmd/structlayout-optimize/main.go\nsrc/honnef.co/go/tools/cmd
/gosimple/gosimple.go\nsrc/honnef.co/go/tools/cmd/gosimple/README.md\nsrc/honnef.co/go/tools/cmd/keyify/keyify.go\nsrc/h
onnef.co/go/tools/cmd/keyify/go-keyify.el\nsrc/honnef.co/go/tools/cmd/keyify/README.md\nsrc/honnef.co/go/tools/cmd/keyif
y/position.go\nsrc/honnef.co/go/tools/cmd/structlayout/README.md\nsrc/honnef.co/go/tools/cmd/structlayout/main.go\nsrc/h
onnef.co/go/tools/ssautil/ssautil.go\nsrc/honnef.co/go/tools/lint/testdata/src/Test/file-ignores.go\nsrc/honnef.co/go/to
ols/lint/testdata/src/Test/line-ignores.go\nsrc/honnef.co/go/tools/lint/generated.go\nsrc/honnef.co/go/tools/lint/LICENS
E\nsrc/honnef.co/go/tools/lint/lint_test.go\nsrc/honnef.co/go/tools/lint/lintdsl/lintdsl.go\nsrc/honnef.co/go/tools/lint
/lintutil/util_test.go\nsrc/honnef.co/go/tools/lint/lintutil/util.go\nsrc/honnef.co/go/tools/lint/lintutil/format/format
.go\nsrc/honnef.co/go/tools/lint/lint.go\nsrc/honnef.co/go/tools/lint/testutil/util.go\nsrc/honnef.co/go/tools/go/types/
typeutil/identical.go\nsrc/honnef.co/go/tools/go/types/typeutil/callee_test.go\nsrc/honnef.co/go/tools/go/types/typeutil
/example_test.go\nsrc/honnef.co/go/tools/go/types/typeutil/methodsetcache.go\nsrc/honnef.co/go/tools/go/types/typeutil/i
mports.go\nsrc/honnef.co/go/tools/go/types/typeutil/callee.go\nsrc/honnef.co/go/tools/go/types/typeutil/ui.go\nsrc/honne
f.co/go/tools/go/types/typeutil/map_test.go\nsrc/honnef.co/go/tools/go/types/typeutil/map.go\nsrc/honnef.co/go/tools/go/
types/typeutil/ui_test.go\nsrc/honnef.co/go/tools/go/types/typeutil/imports_test.go\nsrc/honnef.co/go/tools/staticcheck/
testdata/src/CheckUnmarshalPointer/CheckUnmarshalPointer.go\nsrc/honnef.co/go/tools/staticcheck/testdata/src/CheckInfini
teRecursion/CheckInfiniteRecursion.go\nsrc/honnef.co/go/tools/staticcheck/testdata/src/CheckMathInt/CheckMathInt.go\nsrc
/honnef.co/go/tools/staticcheck/testdata/src/CheckTestMainExit-1/CheckTestMainExit-1.go\nsrc/honnef.co/go/tools/staticch
eck/testdata/src/CheckUnreadVariableValues/CheckUnreadVariableValues_test.go\nsrc/honnef.co/go/tools/staticcheck/testdat
a/src/CheckUnreadVariableValues/CheckUnreadVariableValues.go\nsrc/honnef.co/go/tools/staticcheck/testdata/src/CheckWrite
rBufferModified/CheckWriterBufferModified.go\nsrc/honnef.co/go/tools/staticcheck/testdata/src/CheckCyclicFinalizer/Check
CyclicFinalizer.go\nsrc/honnef.co/go/tools/staticcheck/testdata/src/CheckRangeStringRunes/CheckRangeStringRunes.go\nsrc/
honnef.co/go/tools/staticcheck/testdata/src/checkStdlibUsageNilContext/checkStdlibUsageNilContext.go\nsrc/honnef.co/go/t
ools/staticcheck/testdata/src/CheckTimeSleepConstant/CheckTimeSleepConstant.go\nsrc/honnef.co/go/tools/staticcheck/testd
ata/src/checkStdlibUsageSeeker/checkStdlibUsageSeeker.go\nsrc/honnef.co/go/tools/staticcheck/testdata/src/CheckNilMaps/C
heckNilMaps.go\nsrc/honnef.co/go/tools/staticcheck/testdata/src/CheckConcurrentTesting/CheckConcurrentTesting.go\nsrc/ho
-- More --
```

I find that LeaderfFile works within a git repo for MacVim because it actually runs ```git ls-files  "." && git ls-files --others --exclude-standard  "."'```.


Both ```:py3 print (subprocess.Popen('git ls-files  "." && git ls-files --others --exclude-standard  "."', shell=True, stdout=subprocess.PIPE).stdout.read())``` and ```:!git ls-files  "." && git ls-files --others --exclude-standard  "."```work totally fine.

Also ```:!ag --nocolor --silent -g "" "."``` works well but ```:py3 print (subprocess.Popen('ag --nocolor --silent -g "" "." ', shell=True, stdout=subprocess.PIPE).stdout.read())``` outputs ```b''``.

I'm not sure if it's a the_silver_searcher related issue?

**Comment by Yggdroot** [comment] 2019-05-27 09:13
The issue should be the same as https://github.com/vim/vim/issues/3236, please use rg instead of ag.

**Comment by Yggdroot** [comment] 2019-05-27 09:16
Duplicate of #190 .

**Comment by wangyandong-ningxia** [comment] 2019-05-27 09:34
> The issue should be the same as [vim/vim#3236](https://github.com/vim/vim/issues/3236), please use rg instead of ag.

Thanks for the quick response. rg works great.

**Closed** 2019-05-27 09:36 UTC
Labels: duplicate

**Comment by eirnym** [comment] 2020-12-12 09:35
As per discussion in macvim-dev/macvim#1003 it's a bug in `LeaderF` itself and this issue should be reopened.

**Comment by Yggdroot** [comment] 2020-12-14 13:31
> As per discussion in [macvim-dev/macvim#1003](https://github.com/macvim-dev/macvim/issues/1003) it's a bug in `LeaderF` itself and this issue should be reopened.

Thanks, the issue is fixed.
