### ISSUE TITLE
Arrow keys no longer traverse result list in Insert mode.

### ISSUE THREAD

**Issue by junkdeck** [Yggdroot/LeaderF#240] opened 2018-11-06 11:05 UTC
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
 VIM - Vi IMproved 8.1 (2018 May 17, compiled May 22 2018 11:49:39)
- Output of `:echo has("python")`: 
1
- Output of `:echo has("python3")`: 
0
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
```
2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516]
```

- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

After updating plugin, using arrow keys to navigate result list in "Insert" mode no longer works. 
Instead of traversing the list of results, it traverses the input history.

Ctrl+J/K still works, arrow keys in "Normal" mode still works.

For reference, FZF/Ag still works with arrow key navigation.

### Steps to reproduce

`Open LeaderF search window`
`Input search query`
`Use arrow keys`

### Actual behaviour

Traverses input history.

### Expected behaviour

Should traverse the result list.

**Comment by Yggdroot** [comment] 2018-11-06 11:34
This is a duplicate of issue #236.

**Closed** 2018-11-07 01:40 UTC
Labels: duplicate
