### ISSUE TITLE
新打开一个标签页后，leaderF file popup异常

### ISSUE THREAD

**Issue by panpansuannai** [Yggdroot/LeaderF#825] opened 2021-06-27 14:57 UTC
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
```NVIM v0.5.0-dev+1233-g82ac44d01
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az73-911

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```
- Output of `:echo has("python")`: 
- 0
- Output of `:echo has("python3")`: 
- 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- no python provider
- Output of `:py3 print(sys.version)`: 
- 3.9.5 (default, May 24 2021, 12:50:35)                                                                       
[GCC 11.1.0]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
在一个标签页编辑c++源代码(使用coc-clangd)，但是有错误，coc-clangd会提示，如下图
![image](https://user-images.githubusercontent.com/59492930/123548940-85d18100-d799-11eb-8eb8-2ba08010c1bb.png)
，这时打开一个新标签页，调用leaderF file的popup窗口，会出错，如下 
![image](https://user-images.githubusercontent.com/59492930/123548948-8ec25280-d799-11eb-8135-a59cdced6364.png)
如果把提示的异常代码cli.py中的text变量，如下图
![image](https://user-images.githubusercontent.com/59492930/123549193-7a328a00-d79a-11eb-9aaf-60a66cfa90ca.png)
修改成
![image](https://user-images.githubusercontent.com/59492930/123549250-bf56bc00-d79a-11eb-840e-b680914c57a3.png)
python不会产生异常.

**Comment by Yggdroot** [comment] 2021-06-27 23:33
duplicate of #826 .

**Closed by Yggdroot** 2021-06-27 23:33 UTC
