### ISSUE TITLE
有乱码

### ISSUE THREAD

**Issue by pengfei842852593** [Yggdroot/LeaderF#969] opened 2022-11-22 14:49 UTC
- vim or neovim? 
    - [1] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): /ic/app/c7/miniconda/envs/python3.8/bin/python3
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.8.3 (default, May 19 2020, 18:47:26) [GCC 7.3.0]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [1] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
question: 乱码问题，请求支援
<img width="254" alt="image" src="https://user-images.githubusercontent.com/62005120/203344198-0b9250ce-849c-4a97-a2b8-3b8b4b2de0d3.png">

**Comment by Yggdroot** [comment] 2022-11-24 03:05
Duplicate of #567 .

**Closed** 2022-11-24 05:12 UTC
